Update index.d.ts
Fix `node_modules/supports-webp/index.d.ts(1,16): error TS2693: 'boolean' only refers to a type, but is being used as a value here.`